version = 1
SPDX-PackageName = "ui5-flush-game"
SPDX-PackageSupplier = "SAP OpenUI5 <openui5@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/ui5-flush-game"
SPDX-PackageComment = "The code in this project may include calls to APIs (“API Calls”) of\n SAP or third-party products or services developed outside of this project\n (“External Products”).\n “APIs” means application programming interfaces, as well as their respective\n specifications and implementing code that allows software to communicate with\n other software.\n API Calls to External Products are not licensed under the open source license\n that governs this project. The use of such API Calls and related External\n Products are subject to applicable additional agreements with the relevant\n provider of the External Products. In no event shall the open source license\n that governs this project grant any rights in or to any External Products,or\n alter, expand or supersede any terms of the applicable additional agreements.\n If you have a valid license agreement with SAP for the use of a particular SAP\n External Product, then you may make use of any API Calls included in this\n project’s code for that SAP External Product, subject to the terms of such\n license agreement. If you do not have a valid license agreement for the use of\n a particular SAP External Product, then you may only make use of any API Calls\n in this project for that SAP External Product for your internal, non-productive\n and non-commercial test and evaluation of such API Calls. Nothing herein grants\n you any rights to use or access any SAP External Product, or provide any third\n parties the right to use of access any SAP External Product, through API Calls."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2019 SAP SE or an SAP affiliate company and ui5-flush-game contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "webapp/thirdparty/Box2D.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2006-2007 Erin Catto"
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = ["webapp/thirdparty/createjs.min.js", "webapp/thirdparty/balls.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2015 gskinner.com, inc."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "webapp/thirdparty/dom-to-image.min.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 Anatolii Saienko, 2012 Paul Bakaus"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "webapp/sounds/344445__reidedo__ram-mouth-hawk-rev-v1.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by reidedo (https://freesound.org/people/reidedo/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: RAM_Mouth Hawk_rev_v1.wav (https://freesound.org/people/reidedo/sounds/344445/)"

[[annotations]]
path = "webapp/sounds/243020__plasterbrain__game-start.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 by plasterbrain (https://freesound.org/people/plasterbrain/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: Game Start (https://freesound.org/people/plasterbrain/sounds/243020/)"

[[annotations]]
path = "webapp/sounds/344310__musiclegends__laser-shoot.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by MusicLegends (https://freesound.org/people/MusicLegends/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Laser shoot (https://freesound.org/people/MusicLegends/sounds/344310/)"

[[annotations]]
path = "webapp/sounds/badHit.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 by stumpbutt (https://freesound.org/people/stumpbutt/)"
SPDX-License-Identifier = "CC-BY-NC-3.0"
SPDX-FileComment = "original sound file: retro explosion sfx.wav (https://freesound.org/people/stumpbutt/sounds/381686/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/laser_hits_robot.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 by stumpbutt (https://freesound.org/people/stumpbutt/)"
SPDX-License-Identifier = "CC-BY-NC-3.0"
SPDX-FileComment = "original sound file: retro explosion sfx.wav (https://freesound.org/people/stumpbutt/sounds/381686/)"

[[annotations]]
path = "webapp/sounds/beep_loose.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by cabled_mess (https://freesound.org/people/cabled_mess/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: Lose_Funny_Retro_Video Game (https://freesound.org/people/cabled_mess/sounds/371451/)"

[[annotations]]
path = "webapp/sounds/beep_win.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by LittleRainySeasons (https://freesound.org/people/LittleRainySeasons/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: good_end.mp3 (https://freesound.org/people/LittleRainySeasons/sounds/342218/)"

[[annotations]]
path = "webapp/sounds/game_over2.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by Rocotilos (https://freesound.org/people/Rocotilos/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: 8-bit \"Game Over\" (https://freesound.org/people/Rocotilos/sounds/339837/)"

[[annotations]]
path = "webapp/sounds/goodHit.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by original_sound (https://freesound.org/people/original_sound/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Confirmation Common (https://freesound.org/people/original_sound/sounds/366108/)"

[[annotations]]
path = "webapp/sounds/hammer.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2010 by tec_studio (https://freesound.org/people/tec_studio/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: hamr_BoxTom.wav (https://freesound.org/people/tec_studio/sounds/106861/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/Lasershot.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 by soundslikewillem (https://freesound.org/people/soundslikewillem/)"
SPDX-License-Identifier = "CC-BY-NC-3.0"
SPDX-FileComment = "original sound file: Laser gun (https://freesound.org/people/soundslikewillem/sounds/190707/)"

[[annotations]]
path = "webapp/sounds/Raketenduese.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by InspectorJ (https://freesound.org/people/InspectorJ/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: White Noise, Low Colour, A.wav (https://freesound.org/people/InspectorJ/sounds/361528/)"

[[annotations]]
path = "webapp/sounds/RenderManagerGrowl.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 by cylon8472 (https://freesound.org/people/cylon8472/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Cthulhu growl.wav (https://freesound.org/people/cylon8472/sounds/249686/)"

[[annotations]]
path = "webapp/sounds/RenderManagerLachtTeuflisch.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by newagesoup (https://freesound.org/people/newagesoup/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: monster-laugh (https://freesound.org/people/newagesoup/sounds/337164/)"

[[annotations]]
path = "webapp/sounds/robovoice_loose.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by Rocotilos (https://freesound.org/people/Rocotilos/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: 8-bit \"You Lose\" (https://freesound.org/people/Rocotilos/sounds/339835/)"

[[annotations]]
path = "webapp/sounds/robovoice_start.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by Rocotilos (https://freesound.org/people/Rocotilos/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: 8-bit \"Start\" (https://freesound.org/people/Rocotilos/sounds/339836/)"

[[annotations]]
path = "webapp/sounds/robovoice_win.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 by Rocotilos (https://freesound.org/people/Rocotilos/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: 8-bit \"You Win\" (https://freesound.org/people/Rocotilos/sounds/339834/)"

[[annotations]]
path = "webapp/sounds/start_any_gamelevel.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 by Kodack (https://freesound.org/people/Kodack/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: Arcade Bleep Sound (https://freesound.org/people/Rocotilos/sounds/339834/)"

[[annotations]]
path = "webapp/sounds/Windpfeifen.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009 by Benboncan (https://freesound.org/people/Benboncan/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Wind On Door Short.wav (https://freesound.org/people/zimbot/sounds/209984/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/Bomb.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 by zimbot (https://freesound.org/people/zimbot/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: ExplosionBombBlastAmbientE.wav (https://freesound.org/people/zimbot/sounds/209984/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/LoadControlGun.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 by 18hiltc (https://freesound.org/people/18hiltc/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Alien Bomb Timer.wav (https://freesound.org/people/18hiltc/sounds/208532/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/controls_collision.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2005 by NoiseCollector (https://freesound.org/people/NoiseCollector/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: PongBlipF4.wav (https://freesound.org/people/NoiseCollector/sounds/4359/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/Controlshot.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 by dreeke (https://freesound.org/people/dreeke/)"
SPDX-License-Identifier = "CC-BY-NC-3.0"
SPDX-FileComment = "original sound file: champaign cork.mp3 (https://freesound.org/people/dreeke/sounds/140705/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/cork.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2006 by Traveler (https://freesound.org/people/Traveler/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Cork3.aif (https://freesound.org/people/Traveler/sounds/16064/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/laser_hits_control.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 by coby12388 (https://freesound.org/people/coby12388/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: BombHit01.wav (https://freesound.org/people/coby12388/sounds/222575/)"

[[annotations]]
path = "webapp/sounds/sounds_multiplayer/Vogelgezwitscher.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 by PLukx (https://freesound.org/people/PLukx/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: FX_bird_water_whistle.wav (https://freesound.org/people/PLukx/sounds/254209/)"

[[annotations]]
path = "webapp/sounds/RenderManagerVomBlitzGetroffenDonner.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 by bajko (https://freesound.org/people/bajko/)"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "original sound file: sfx_thunder blast.wav (https://freesound.org/people/bajko/sounds/399656/)"

[[annotations]]
path = "webapp/sounds/Musik_Tristan.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 by Tristan_Lohengrin (https://freesound.org/people/Tristan_Lohengrin/)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: 8bit Introduction (https://freesound.org/people/Tristan_Lohengrin/sounds/399656/)"

[[annotations]]
path = "webapp/sounds/Jingle_Bells_3.mp3"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 by Kevin MacLeod (https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100187)"
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = "original sound file: Jingle Bells.mp3 (https://incompetech.com/music/royalty-free/mp3-royaltyfree/Jingle%20Bells.mp3)"
